# Generated by Django 4.2.5 on 2023-09-30 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='description',
        ),
        migrations.RemoveField(
            model_name='review',
            name='developer',
        ),
        migrations.RemoveField(
            model_name='review',
            name='reviews',
        ),
    ]
